### ISSUE TITLE
BLAS vendor

### ISSUE THREAD

**Issue by simonpintarelli** [eth-cscs/spla#5]
SPLA will always link against MKL if it's present, for example also with `spack install spla ^openblas`. Also the spack package.py should be changed accordingly, such that the BLAS vendor is read from `spec['blas'].name` and forwrded to SPLA cmake.

**Comment by AdhocMan** [comment]
Sorry for not responding sooner, I did not have notifications on for this repository somehow. This should be fixed with the new release and the spack package will be updated soon.
